name: 同步k1995-GitHub油猴汉化插件仓库
on:
  schedule:
    - cron: '5 10 */5 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-k1995-github-i18n-plugin
     
env:
  PAT: ${{ secrets.PAT }} 
  SERVERCHAN_SCKEY: true
  TZ: Asia/Shanghai  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: 电报通知
        if: env.SERVERCHAN_SCKEY == 'true'
        run: |
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=🎉 主人：开始为您同步k1995-github-i18n-plugin仓库,请耐心等待...... 😋" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
       
      - name: sync k1995-github-i18n-plugin
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/k1995/github-i18n-plugin.git"
          source_branch: "master"
          destination_branch: "k1995"
          github_token: ${{ secrets.PAT }}
          
      - name: 电报通知
        if: env.SERVERCHAN_SCKEY == 'true'
        run: |
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=我亲爱的✨主人✨：您同步的k1995-github-i18n-plugin仓库顺利同步完成了！💐" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
