name: 同步zbezj-HEU_KMS_Activator仓库
on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-zbezj-HEU_KMS_Activator
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync zbezj-HEU_KMS_Activator
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/zbezj/HEU_KMS_Activator.git"
          source_branch: "master"
          destination_branch: "zbezj"
          github_token: ${{ secrets.PAT }}
